#goal definion
geometry_msgs/Pose setPoseGoalBusyGenius
geometry_msgs/Twist setTwistGoalBusyGenius
---
#result definition
string end
geometry_msgs/Pose getTwist
geometry_msgs/Pose getPose
---
#feedback
geometry_msgs/Pose getPoseOfBusyGenius
geometry_msgs/Twist getTwistOfBusyGenius
